name: Sourcegraph
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lsif:
    runs-on: ubuntu-latest
    name: "Upload LSIF"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.6"
      - run: |
          mkdir -p bin
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o bin/src
          chmod +x bin/src
          export PATH="$PATH:$PWD/bin"
          sbt \
              'set every semanticdbEnabled := true' \
              'set every semanticdbVersion := "4.4.24"' \
              sourcegraphUpload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
